name: Deploy Captain Bayes Notebooks
on:
    push:
        branches:
            - deploy
    workflow_dispatch:

jobs:
    deploy-pages:
        name: Deploy Github Pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.5
            - name: Run Pluto notebooks
              run: julia --project=bind-server-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  import PlutoUtils;
                  PlutoUtils.Export.github_action(; export_dir=".", baked_state=false, offer_binder=true, bind_server_url="https://bayes.sieberer.me");'

            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: deploy-output
                  FOLDER: .
    build-docker:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.CR_PAT }}
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/amd64
              push: true
              tags: |
                captain-bayes/bind-server:latest
                ghcr.io/captain-bayes/bind-server:latest